name: vetscapes
favicon: null
layout_spectrum: 0.7180628255009651
typography_spectrum: 0.48586506489664316
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.1650443773251027
  lightness: 0.7879658294841647
  saturation: 0.03392714844085276
  rhythmicContrast: 0.7995810403954238
purpose: []
